description: Compile Application
arguments:
  app:
    name: app
    mode: 1
    description: 'Path to executable application. Eg: bin/app'
options:
  project-path:
    name: project-path
    shortcut: p
    mode: 4
    default:
    description: 'Path to project directory'
  config-path:
    name: config-path
    shortcut: c
    mode: 4
    default:
    description: 'Path to configuration directory'
  build-version:
    name: build-version
    shortcut: b
    mode: 4
    default:
    description: 'Build Version'
  build-date:
    name: build-date
    shortcut: d
    mode: 4
    default:
    description: 'Build Date'
  exclude-file:
    name: exclude-file
    # Mode: Optional array.
    mode: 12
    default:
    description: 'Exclude files'
  no-compress:
    name: no-compress
    mode: 16
    description: 'Do not compress files'
  no-optimize:
    name: no-optimize
    mode: 16
    description: 'Do not optimize class map'
  no-executable:
    name: no-executable
    mode: 16
    description: 'Do not create executable file'
  no-hidden-input:
    name: no-hidden-input
    # Mode: Optional flag
    mode: 16
    description: "Exclude symfony console's hiddeninput.exe"
  no-cache:
    name: no-cache
    # Mode: Optional flag
    mode: 16
    description: "Do not cache configuration to file"
  phar:
    name: phar
    mode: 16
    description: 'Add .phar extension'
questions:
validators:
  - in2pire.compiler.cli.validator.project-path
  - in2pire.compiler.cli.validator.app
tasks:
  - in2pire.compiler.cli.task.compile
